################################################################################
# Copyright 2018 Centauro centauro.com.br. All rights reserved.
# Author: "Leandro Bezerra" <leandro.bezerra>
#
# Ask developer of testsuite to add profiles where desired.
# This file defines predefined profiles that can be used.
# Example > cucumber -p default -p chrome

<% timestamp = Time.now.strftime("%Y%m%d_%H%M") %>

################################################################################
# Type of testrun
default: -f pretty -x
debug: -f pretty BREAKPOINT_ON_FAILURE=1
html_report: -f pretty -f html --out=results/<%=timestamp%>_report.html
junit_report: -f pretty -f junit --out=results

################################################################################
# Supported browsers (default = firefox)
ff: BROWSER=firefox
firefox: BROWSER=firefox
chrome: BROWSER=chrome